{
 "title": "Flask app SLO SLI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "publicIp", "query": "3.135.206.175" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "90% percentile of all requests complete in less or equal to 100ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.9, sum(rate(flask_http_request_duration_seconds_bucket{instance=\"${publicIp}:80\", status=~\"2.*\"}[10m])) by (le))"
    }
   ]
  },
  {
   "title": "Troughput",
   "type": "timeseries",
   "description": "Successful requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{instance=\"${publicIp}:80\", status=~\"2.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Proportion of number of successful requests against the number of all requests",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{instance=\"${publicIp}:80\", status!~\"5.*\"}[5m]))/sum(rate(flask_http_request_total{instance=\"${publicIp}:80\"}[5m]))"
    }
   ]
  },
  {
   "title": "Remaining Error budget",
   "type": "stat",
   "description": "Used Error budget. The error budget is 20%",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(1-sum(rate(flask_http_request_duration_seconds_count{instance=\"${publicIp}:80\", status=~\"2.*\"}[30d]))/sum(rate(flask_http_request_duration_seconds_count{instance=\"${publicIp}:80\"}[30d])))/0.2"
    }
   ]
  }
 ]
}